### ISSUE TITLE
Typeahead throws exception when clicking twice in the textual area of the control

### ISSUE THREAD

**Issue by simong-hs** [loresoft/LoreSoft.Blazor.Controls#72]
Left click on the text region of the typeahead control (not on the right hand drop down arrow) to drop down the search box and items menu, then without moving the mouse left click again in the same place (to close the drop down). An exception is throw at this point:
Unhandled exception rendering component: Cannot read property 'parentNode' of undefined

This behaviour can be replicated on any of the examples on the demo page:
https://blazor.loresoft.com/typeahead/index

Full exception details:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'parentNode' of undefined
      TypeError: Cannot read property 'parentNode' of undefined
          at Object.e [as removeLogicalChild] (https://localhost:44377/_framework/blazor.webassembly.js:1:10109)
          at e.applyEdits (https://localhost:44377/_framework/blazor.webassembly.js:1:32821)
          at e.updateComponent (https://localhost:44377/_framework/blazor.webassembly.js:1:32052)
          at Object.t.renderBatch (https://localhost:44377/_framework/blazor.webassembly.js:1:11924)
          at Object.window.Blazor._internal.renderBatch (https://localhost:44377/_framework/blazor.webassembly.js:1:61687)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44377/_framework/blazor.webassembly.js:1:64209)
          at _mono_wasm_invoke_js_blazor (https://localhost:44377/_framework/dotnet.5.0.3.js:1:190800)
          at wasm_invoke_iiiiii (<anonymous>:wasm-function[5611]:0xdda7f)
          at ves_pinvoke_method (<anonymous>:wasm-function[5708]:0xdfb62)
          at interp_exec_method (<anonymous>:wasm-function[2155]:0x44c08)
Microsoft.JSInterop.JSException: Cannot read property 'parentNode' of undefined
TypeError: Cannot read property 'parentNode' of undefined
    at Object.e [as removeLogicalChild] (https://localhost:44377/_framework/blazor.webassembly.js:1:10109)
    at e.applyEdits (https://localhost:44377/_framework/blazor.webassembly.js:1:32821)
    at e.updateComponent (https://localhost:44377/_framework/blazor.webassembly.js:1:32052)
    at Object.t.renderBatch (https://localhost:44377/_framework/blazor.webassembly.js:1:11924)
    at Object.window.Blazor._internal.renderBatch (https://localhost:44377/_framework/blazor.webassembly.js:1:61687)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44377/_framework/blazor.webassembly.js:1:64209)
    at _mono_wasm_invoke_js_blazor (https://localhost:44377/_framework/dotnet.5.0.3.js:1:190800)
    at wasm_invoke_iiiiii (<anonymous>:wasm-function[5611]:0xdda7f)
    at ves_pinvoke_method (<anonymous>:wasm-function[5708]:0xdfb62)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x44c08)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by pwelter34** [comment]
I've made some improvements.  Can you try again and see if this is still an issue.  Thanks

**Comment by simong-hs** [comment]
That issue is fixed now, many thanks
